# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b1257c4b7d4962fd60ea813be9df863ad412efb799dfa78922903f44d1d2156db8852deaed6da673363c984d81fb60c8bc0ffae1e7018280f22f8292425e0bf1

test:
  secret_key_base: 24cb68c0e7eb8696fb9ee3512e1b22038f260e99ece22b12b2b7c60c326f6bb4d268f67d0ba749fa4c85e2603f589fb371135170b1d3a18e12cda0f975bd1ec3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
